name: maven

on:
  push:
    branches: [ '1.6.X', master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 9, 10, 11, 12, 13, 14, 15, 16, 17 ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - run: mvn -B package --file pom.xml
